name: Publish PyPi

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Publish platform"
        required: true
        default: "testpypi"
        type: choice
        options: ["testpypi", "pypi"]
      python-version:
        description: "Python version used for build"
        required: false
        default: "3.11"
        type: string

permissions:
  contents: read
  
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip && python -m pip install "cibuildwheel~=3.3"

      - name: Build wheels
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_BEFORE_ALL_MACOS: "bash ./build.sh"
          CIBW_BEFORE_ALL_WINDOWS: "bash build.sh"
          CIBW_BEFORE_ALL_LINUX: >
            curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh &&
            bash ./dotnet-install.sh --version latest &&
            bash ./build.sh
          CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.dotnet:$PATH DOTNET_ROOT=$HOME/.dotnet"
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: ""
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - run: python -m pip install --upgrade pip build
      - run: python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  publish:
    name: Publish to ${{ inputs.target }}
    runs-on: ubuntu-latest
    needs: [build_wheels, sdist]

    permissions:
      id-token: write
      contents: read

    # Ignore environment at the moment
    #environment:
    #  name: ${{ inputs.target }}

    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: cibw-wheels-*
          path: dist/
          merge-multiple: true

      - uses: actions/download-artifact@v5
        with:
          name: sdist
          path: dist/

      - name: Show artifacts to upload
        run: ls -l dist

      - name: Publish distributions
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # This is set by default to PyPI
          repository-url: ${{ inputs.target == 'testpypi' && 'https://test.pypi.org/legacy/' || '' }}
          skip-existing: true
